kind: "API"
version: "1"
metadata:
  envTypes: ["dev", "stage", "prod"]
data:
  allowedClientIDs:
    author:
      - "aem-extension-builder"
      - "ecf1d288306b42adaa67972f00b05080"
      - "aem-oauth-claude"
    publish:
      - "ecf1d288306b42adaa67972f00b05080"
    preview:
      - "ecf1d288306b42adaa67972f00b05080"