kind: "API"
version: "1"
metadata:
  envTypes: ["dev", "stage", "prod"]
data:
  allowedClientIDs:
    author:
      - "aem-extension-builder"
      - "c2de13d297f649d38d3329695ef22b59"
    publish:
      - "c2de13d297f649d38d3329695ef22b59"
    preview:
      - "c2de13d297f649d38d3329695ef22b59"